### PR TITLE
Add an option for smart selection conversion

### PR DESCRIPTION
**Pull request by lubokkanev**
Make it possible to convert not only the last word, but the last text paragraph that was entered. 

This seems to be my most frequent scenario: I change to some app and I misjudge the current layout. I start typing and mid sentence I want to convert the whole paragraph I've just written. Only the last word doesn't suffice. 

I've added a checkbox that enables this behavior. If it's checked, space doesn't reset the selection that will be converted.

### CODE REVIEW

**Comment by BladeMight** [comment]
Well hello there @lubokkanev , thanks but dotSwitcher is already discontinued, so pull requests won't be merged...
I recommend you to take a look at [Mahou](https://github.com/BladeMight/Mahou) which I created inspired by this project, it has all the features you need, and much more...

Happy converting.

**Comment by kurumpa** [comment]
Thanks! However, it turns out my switcher is buggy in so many ways :)

**Comment by kurumpa** [comment]
@BladeMight Haha merged :p

**Comment by lubokkanev** [comment]
@BladeMight  @kurumpa I'll check out Mahou, but dotSwitcher works great for me. :)

**Pull request merged**
