### PR TITLE
Implement UI in WPF

### PR DESCRIPTION
**Pull request by programmer-1**
Changelog:
------------------------------------------------
1- implement UI in WPF.
2- make major change in User Interface.
3- Add about button.
4- add screenshot to Readme.md.
5- some cleaning code.
Tested on Release/Debug mode, there was no problem.

Possible improvements in future:
------------------------------------------------
Reimplement current code in MVVM pattern.

A few suggestions:
------------------------------------------------
1- In my opinion "Show tray icon " not needed. when there isn't tray icon, Reshowing is  difficult.

2- only  changing last word isn't enough, Users typically realized their's mistake after some words.

I'm sorry for my poor English.
Goodluck.

### CODE REVIEW

**Comment by programmer-1** [comment]
did you reviewed the branch?

**Comment by kurumpa** [comment]
Hey Sayyid,
first of all, thank you for your contribution, i appreciate it a lot! 

I've finally found a little time to spend on this switcher project, so here's my point. I don't really like WPF, esp. for small projects. For example, http://stackoverflow.com/a/1015215/944781 - It's simple, they said, just add (several winapi hacks follow!). So i'll try to keep the project both nice-looking and readable with winforms, there's no need for MVVM or stuff like that IMHO. How does that sound to you?

Other options:
> 2- make major change in User Interface.

I'm still working on UI improvements, so your suggestions will certainly be helpful for it.

>3- Add about button.

Still not sure about it.

>4- add screenshot to Readme.md.

That's a good point!

>5- some cleaning code.

I'm finishing a massive refactoring at the moment :)

>1- In my opinion "Show tray icon " not needed. when there isn't tray icon, Reshowing is difficult.

That was a user request and it makes sense for me. I'd better hide this option but not completely remove it

>2- only changing last word isn't enough, Users typically realized their's mistake after some words.

Converting the selection will do, i suppose. Or do you have any specific thought about how it could work? 

Anyway, thanks again for both helping and understanding me :sunglasses:

**Comment by programmer-1** [comment]
Hi again.
Thank for your reply.
Okay.this project is small but it's not good reason to avoid new technologies like wpf. And also I do not agree with your view that wpf is not for small project. For small project mvvm isn't recommended not wpf!
However wpf possible sophisticated in first view but realy it isn't complex at least for small project that not use mvvm pattern and it will make ui modification easier and code more cleaner.
Of course project is yours and your decision is respected.
One another option is adding auto switcher. We can add checkbox to ui with name "smart switch" when this option activated, program record user behaviur and make auto switch in future. For example you anytime type word "sdxvg" after that use pause key to switch, if this behaviur repeated for example six times it's mean we can auto switch after this word then add this word to light database (xml based or json and so on) and use it to smart switch.
I dont think alot about this idea but i think its practical.
I Hope you have more time to have faster feedback. :)
Good luck.

**Comment by kurumpa** [comment]
Thanks, Sayyid. Not a big deal with this UI, it's just a set of inputs after all :) 
About behavior-driven auto switching - that's a good point. Punto offers an option to auto-switch always (based on language possible letter sequence) but everyone hates this functionality as far as i know. Cheers!

**Pull request closed without merging**
